In [ ]:
from dataclasses import replace

import pa

In [26]:
import pandas as pd

In [ ]:
sr=pd.Series(["a","b","c"])

In [ ]:
sr

In [ ]:
sr1=pd.Series(["ahmad","python","class"],index=["*","=","!"])#optional perimeter index

In [ ]:
sr1

In [ ]:
print("ahmad",end="")#print command perimeterr

In [ ]:
sr2=pd.Series(["val1","val2","val3"],index=["*","=","(_)"])
sr2

In [ ]:
di={"name":["ali","ahmad","arbab"],"age":[21,22,23]}
di

In [ ]:
df=pd.DataFrame(di)#dataframe short variable

In [ ]:
df

In [ ]:
df.to_csv("ClasFirstTable.csv")

In [27]:
dfItems=pd.read_excel("VendorProducts.xlsx")

In [28]:
dfItems

,Picture,Id,Name,Secondary Name,Barcode,Code,Price,Description,Secondary Description,Sub Description,Secondary Sub Description,Menu,Brand,Secondary Brand,Has Collections
0,https://www.storeakmedia.com/storeak-erp/Store...,390188,زيت الشفاه بليجر 001، 5 مل,"Pleasure Lip Oil 001, 5 ml",8011607402304,NaN,"25,000د.ع","زيت مغذي للشفاه, يُعزز لمعان الشفاه بتأثير بصر...",Nourishing lip oil that enhances lip shine wit...,|بوبا ميلانو|Pupa Milano|Lip Oil|زيت الشفاه|زي...,NaN,العناية بالبشرة‎ -> الشفاه‎ -> زيوت,بوبا ميلانو,Pupa Milano,No
1,https://www.storeakmedia.com/storeak-erp/Store...,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,NaN,"300,000د.ع",عطر أروماتك إنيق للرجال.\nمكونات العطر: العنبر...,An elegant aromatic fragrance for men.\nFragra...,|شانيل|Chanel|العطور|Perfumes|عطر للرجال|عطر ر...,NaN,"العطور‎ -> رجالي‎ -> العطور,private group‎ -> ...",شانيل,Chanel,Yes
2,https://www.storeakmedia.com/storeak-erp/Store...,390186,سيروم الشعر لفروة الرأس سيابوري 20 مل,Seapuri Scalpy Hair Serum 20 ml,8809934860870,NaN,"30,000د.ع",سيروم خفيف الوزن وغير دهني يعالج تساقط الشعر و...,"A lightweight, non greasy serum that treats ha...",|Others|اخرى|hair loss Serum|سيروم تساقط الشعر...,NaN,الشعر‎ -> العناية بالشعر‎ -> تساقط الشعر‎ -> س...,اخرى,Others,No
3,https://www.storeakmedia.com/storeak-erp/Store...,390185,عطر جانيميد اودي بارفيوم 50 مل,Ganymede EDP 50 ml,3770006409141,NaN,00د.ع,"عطر شرقي حار للجنسين.\nمقدمة العطر: البخور, ال...",An oriental spicy fragrance for both sexes.\nT...,|Marc-Antoine Barois Paris|مارك أنطوان باروا ب...,NaN,"العطور‎ -> نسائي‎ -> العطور,العطور‎ -> رجالي‎ ...",مارك انطوان باروا باريس,Marc-Antoine Barrois Paris,No
4,https://www.storeakmedia.com/storeak-erp/Store...,390177,جل تصفيف الحواجب مع الببتيدات 15 مل,Brow Styling Gel With Peptides 15 ml,8056814230036,NaN,"15,000د.ع",امنحي حواجبك شكلاً أنيقًا يدوم طوال اليوم مع ج...,"Give your brows a sleek, all day shape with ou...",|Ayten|أيتن|Eyebrow Gel|جل الحواجب|جل تصفيف ال...,NaN,المكياج‎ -> الحواجب‎ -> جل,آيتن,Ayten,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24697,https://www.storeakmedia.com/storeak-erp/Store...,315019,معطر الشعر والجسم بالليمون والماتشا 150 مل,Lime & Matcha Hair & Body Mist 150 ml,5028197838058,0,"16,500د.ع","زذاذ معطر الجسم والشعر منعش وفواح, يتكون من مز...","A refreshing and fragrant body and hair mist, ...",|ذا بودي شوب|The Body Shop|عطور الشعر|Hair Per...,NaN,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24698,https://www.storeakmedia.com/storeak-erp/Store...,315018,معطر الشعر والجسم بالفلفل الوردي والليتشي 150 مل,Pink Pepper & Lychee Hair & Body Mist 150 ml,5028197930516,0,"12,000د.ع","رذاذ معطر الجسم والشعر جذاب ومنعش للنساء, يمتا...",An attractive and refreshing body and hair mis...,|ذا بودي شوب|The Body Shop|عطور الشعر|Hair Per...,NaN,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24699,https://www.storeakmedia.com/storeak-erp/Store...,314993,ماسكارا جلام اند دول تعزز نمو الرموش 8 مل,Glam & Doll Boost Lash Growth Volume Mascara 8 ml,4059729191380,0,"10,500د.ع","ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...","Mascara features a brush with thick bristles, ...",|كاتريس|Catrice|ماسكارا عادية| Mascara‎ Normal...,NaN,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,كاتريس,Catrice,No
24700,https://www.storeakmedia.com/storeak-erp/Store...,314992,مست الجسم باشن فروت 150 مل,Body Mist Passion Fruit150 ml,5283024103017,0,"15,000د.ع","رذاذ معطر للجسم, يساعدك على الشعور بالانتعاش و...",A body mist that helps you feel fresh and conf...,|بيت الصابون اللبناني|Bayt Al Saboun|العناية ب...,NaN,"العناية بالجسم‎ -> سبلاش,private group‎ -> مين...",بيت الصابون اللبناني,Bayt Al Saboun,No
24701,https://www.storeakmedia.com/storeak-erp/Store...,314991,ماسكارا فائقة الكثافة (1أسود) 15 مل,Volume Supreme Mascara (1Black) 15 ml,4052136039429,0,"22,500د.ع","ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...",Mascara is characterized by its thick bristled...,|آرتديكو|Artdeco|ماسكارا عادية| Mascara‎ Norma...,NaN,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,آرتديكو,Artdeco,No

In [4]:
dfItems=pd.read_excel("VendorProducts.xlsx",sheet_name="Items")
dfItems

NameError: name 'pd' is not defined

In [5]:

print(dfItems["Item Name"])

NameError: name 'dfItems' is not defined

In [ ]:
dfItems=pd.read_excel("VendorProducts.xlsx",sheet_name="Collections")
dfItems

In [ ]:
print(dfItems["Price"])

In [57]:
MessyPrice =  list(dfItems["Price"])
CleanedPrice = []
for price in MessyPrice:
   price = price.replace("د.ع","")
   price = price.replace(",","")
   CleanedPrice.append(int(price))

In [66]:
cleanedPrice

In [67]:
dfItems["Price"]=CleanedPrice

In [68]:
dfItems[["Sub Description","Description","Secondary Description"]]

,Sub Description,Description,Secondary Description
0,|بوبا ميلانو|Pupa Milano|Lip Oil|زيت الشفاه|زي...,"زيت مغذي للشفاه, يُعزز لمعان الشفاه بتأثير بصر...",Nourishing lip oil that enhances lip shine wit...
1,|شانيل|Chanel|العطور|Perfumes|عطر للرجال|عطر ر...,عطر أروماتك إنيق للرجال.\nمكونات العطر: العنبر...,An elegant aromatic fragrance for men.\nFragra...
2,|Others|اخرى|hair loss Serum|سيروم تساقط الشعر...,سيروم خفيف الوزن وغير دهني يعالج تساقط الشعر و...,"A lightweight, non greasy serum that treats ha..."
3,|Marc-Antoine Barois Paris|مارك أنطوان باروا ب...,"عطر شرقي حار للجنسين.\nمقدمة العطر: البخور, ال...",An oriental spicy fragrance for both sexes.\nT...
4,|Ayten|أيتن|Eyebrow Gel|جل الحواجب|جل تصفيف ال...,امنحي حواجبك شكلاً أنيقًا يدوم طوال اليوم مع ج...,"Give your brows a sleek, all day shape with ou..."
...,...,...,...
24697,|ذا بودي شوب|The Body Shop|عطور الشعر|Hair Per...,"زذاذ معطر الجسم والشعر منعش وفواح, يتكون من مز...","A refreshing and fragrant body and hair mist, ..."
24698,|ذا بودي شوب|The Body Shop|عطور الشعر|Hair Per...,"رذاذ معطر الجسم والشعر جذاب ومنعش للنساء, يمتا...",An attractive and refreshing body and hair mis...
24699,|كاتريس|Catrice|ماسكارا عادية| Mascara‎ Normal...,"ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...","Mascara features a brush with thick bristles, ..."
24700,|بيت الصابون اللبناني|Bayt Al Saboun|العناية ب...,"رذاذ معطر للجسم, يساعدك على الشعور بالانتعاش و...",A body mist that helps you feel fresh and conf...
24701,|آرتديكو|Artdeco|ماسكارا عادية| Mascara‎ Norma...,"ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...",Mascara is characterized by its thick bristled...

In [69]:
dfItems[(dfItems["Secondary Brand"]=="Nivea") & (dfItems["Price"]>1000)]

,Picture,Id,Name,Secondary Name,Barcode,Code,Price,Description,Secondary Description,Sub Description,Secondary Sub Description,Menu,Brand,Secondary Brand,Has Collections
15,NaN,390143,جل استحمام بزيت جوز الهند والجوجوبا 750 مل,Coconut & Jojoba Oil shower gel 750 ml,4005900998811,NaN,8000,جل استحمام بزيت جوز الهند والجوجوبا يمنحكِ بشر...,Shower gel with coconut and jojoba oil gives y...,|نيفيا|Nivea|العناية بالجسم غسول الجسم|Body Ca...,NaN,العناية بالجسم‎ -> غسول الجسم,نيفيا,Nivea,No
809,https://www.storeakmedia.com/storeak-erp/Store...,359629,بلسم ما بعد الحلاقة للبشرة الحساسة برو ألترا ك...,After Shave Balm Sensitive Pro Ultra Calming 1...,9005800347479,0,9000,بلسم مهدئ البشرة ما بعد الحلاقة، تحتوي تركيبته...,"This soothing aftershave balm, formulated with...",|نيفيا|Nivea|العناية بالرجال بعد الحلاقة|Men C...,NaN,العناية بالرجال‎ -> اللحية‎ -> بعد الحلاقة,نيفيا,Nivea,No
810,https://www.storeakmedia.com/storeak-erp/Store...,359628,جل الاستحمام كريم كير750 مل,Shower Gel Creme Care 750 ml,4006000095752,0,8000,غسول الجسم ينظف بشرتكِ بلطف أثناء الاستحمام، ب...,This body wash gently cleanses your skin while...,|نيفيا|Nivea|العناية بالجسم غسول الجسم|Body Ca...,NaN,العناية بالجسم‎ -> غسول الجسم,نيفيا,Nivea,No
814,https://www.storeakmedia.com/storeak-erp/Store...,359607,جل استحمام كريم سموث 750 مل,Shower Gel Cream Smooth 750 ml,4006000095738,0,8000,جل استحمام يمنحك بشرة نظيفة وناعمة وصحية بشكل ...,"Shower gel that gives you naturally clean, sof...",|نيفيا|Nivea|العناية بالجسم غسول الجسم|Body Ca...,NaN,العناية بالجسم‎ -> غسول الجسم,نيفيا,Nivea,No
815,https://www.storeakmedia.com/storeak-erp/Store...,359606,جل استحمام كريم سوفت 750 مل,Shower Gel Creme Soft 750 ml,4006000095776,0,8000,جل استحمام يمنحك بشرة نظيفة وناعمة وصحية بشكل ...,"Shower gel that gives you naturally clean, sof...",|نيفيا|Nivea|العناية بالجسم غسول الجسم|Body Ca...,NaN,العناية بالجسم‎ -> غسول الجسم,نيفيا,Nivea,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22999,https://www.storeakmedia.com/storeak-erp/Store...,316752,رغوة حلاقة منعشة للبشرة الحساسة 200 مل,Sensitive Cooling Shaving Foam 200 ml,4005900378255,0,6000,"رغوة الحلاقة للرجال, تعمل على تنعيم اللحية لحل...",Men's Shaving Foam Softens the beard for a clo...,|نيفيا|Nivea|العناية بالرجال جل ورغوة الحلاقة|...,NaN,العناية بالرجال‎ -> اللحية‎ -> جل & رغوة الحلاقة,نيفيا,Nivea,No
23063,https://www.storeakmedia.com/storeak-erp/Store...,316688,غسول التنظيف العميق للوجه واللحية 100 مل,Deep Face & Beard Wash Cleanser 100 ml,4005900517951,0,7750,"غسول الوجه للرجال, تركيبة مبتكرة بالفحم الأسود...","Face wash for men, an innovative formula with ...",|نيفيا|Nivea|العناية بالرجال منظف الوجه|Men Ca...,NaN,العناية بالرجال‎ -> الوجه‎ -> منظف الوجه,نيفيا,Nivea,No
23064,https://www.storeakmedia.com/storeak-erp/Store...,316687,غسول منعش للوجه 100 مل,Refreshing Face Wash 100 ml,4005808228010,0,7250,"غسول الوجه للرجال, يزيل الأوساخ والزيوت الزائد...","Face wash for men, removes dirt and excess oil...",|نيفيا|Nivea|العناية بالرجال منظف الوجه|Men Ca...,NaN,العناية بالرجال‎ -> الوجه‎ -> منظف الوجه,نيفيا,Nivea,No
23065,https://www.storeakmedia.com/storeak-erp/Store...,316686,مقشر الوجه ديب بقوة الكاربون 75 مل,Deep Black Carbon Face Scrub 75 ml,4005900678522,0,7750,"مقشر الوجه للرجال, بتركيبة الفحم الأسود التي ت...","Facial scrub for men, with a black carbon form...",|نيفيا|Nivea|العناية بالرجال منظف الوجه|Men Ca...,NaN,العناية بالرجال‎ -> الوجه‎ -> منظف الوجه,نيفيا,Nivea,No
23066,https://www.storeakmedia.com/storeak-erp/Store...,316685,غسول الوجه ديب لازالة الحبوب وزيوت البشرة 100 مل,Deep Pimple & Oil Clear Face Wash 100 ml,4005900818119,0,8500,"غسول الوجه للرجال, يقوم بتنظيف وتنقية البشرة ب...","Facial wash for men, it gently cleanses and pu...",|نيفيا|Nivea|العناية بالرجال منظف الوجه|Men Ca...,NaN,العناية بالرجال‎ -> الوجه‎ -> منظف الوجه,نيفيا,Nivea,No

In [70]:
dfItems.loc[dfItems["Id"]==359629,"Price"]=15000

In [71]:
dfItems[dfItems["Id"]==359629]

,Picture,Id,Name,Secondary Name,Barcode,Code,Price,Description,Secondary Description,Sub Description,Secondary Sub Description,Menu,Brand,Secondary Brand,Has Collections
809,https://www.storeakmedia.com/storeak-erp/Store...,359629,بلسم ما بعد الحلاقة للبشرة الحساسة برو ألترا ك...,After Shave Balm Sensitive Pro Ultra Calming 1...,9005800347479,0,15000,بلسم مهدئ البشرة ما بعد الحلاقة، تحتوي تركيبته...,"This soothing aftershave balm, formulated with...",|نيفيا|Nivea|العناية بالرجال بعد الحلاقة|Men C...,NaN,العناية بالرجال‎ -> اللحية‎ -> بعد الحلاقة,نيفيا,Nivea,No

In [74]:
dfItems[["Secondary Name","Price"]]

                                          Secondary Name   Price
0                             Pleasure Lip Oil 001, 5 ml   25000
1                       Bleu De Chanel L'Exclusif Parfum  300000
2                        Seapuri Scalpy Hair Serum 20 ml   30000
3                                     Ganymede EDP 50 ml       0
4                  Brow Styling Gel With Peptides 15 ml    15000
...                                                  ...     ...
24697              Lime & Matcha Hair & Body Mist 150 ml   16500
24698       Pink Pepper & Lychee Hair & Body Mist 150 ml   12000
24699  Glam & Doll Boost Lash Growth Volume Mascara 8 ml   10500
24700                      Body Mist Passion Fruit150 ml   15000
24701              Volume Supreme Mascara (1Black) 15 ml   22500

[24702 rows x 2 columns]

In [77]:
dfItems["newSecondary name"]=dfItems["Secondary Name"] +" "+str(dfItems["Price"])+"PKR"

In [78]:
dfItems["newSecondary name"]

0        Pleasure Lip Oil 001, 5 ml 0         25000\n1 ...
1        Bleu De Chanel L'Exclusif Parfum 0         250...
2        Seapuri Scalpy Hair Serum 20 ml 0         2500...
3        Ganymede EDP 50 ml 0         25000\n1        3...
4        Brow Styling Gel With Peptides 15 ml  0       ...
                               ...
24697    Lime & Matcha Hair & Body Mist 150 ml 0       ...
24698    Pink Pepper & Lychee Hair & Body Mist 150 ml 0...
24699    Glam & Doll Boost Lash Growth Volume Mascara 8...
24700    Body Mist Passion Fruit150 ml 0         25000\...
24701    Volume Supreme Mascara (1Black) 15 ml 0       ...
Name: newSecondary name, Length: 24702, dtype: str

In [79]:
dfItems.drop(columns=["Secondary Sub Description","Sub Description"])

,Picture,Id,Name,Secondary Name,Barcode,Code,Price,Description,Secondary Description,Menu,Brand,Secondary Brand,Has Collections,newSecondary name
0,https://www.storeakmedia.com/storeak-erp/Store...,390188,زيت الشفاه بليجر 001، 5 مل,"Pleasure Lip Oil 001, 5 ml",8011607402304,NaN,25000,"زيت مغذي للشفاه, يُعزز لمعان الشفاه بتأثير بصر...",Nourishing lip oil that enhances lip shine wit...,العناية بالبشرة‎ -> الشفاه‎ -> زيوت,بوبا ميلانو,Pupa Milano,No,"Pleasure Lip Oil 001, 5 ml 0 25000\n1 ..."
1,https://www.storeakmedia.com/storeak-erp/Store...,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,NaN,300000,عطر أروماتك إنيق للرجال.\nمكونات العطر: العنبر...,An elegant aromatic fragrance for men.\nFragra...,"العطور‎ -> رجالي‎ -> العطور,private group‎ -> ...",شانيل,Chanel,Yes,Bleu De Chanel L'Exclusif Parfum 0 250...
2,https://www.storeakmedia.com/storeak-erp/Store...,390186,سيروم الشعر لفروة الرأس سيابوري 20 مل,Seapuri Scalpy Hair Serum 20 ml,8809934860870,NaN,30000,سيروم خفيف الوزن وغير دهني يعالج تساقط الشعر و...,"A lightweight, non greasy serum that treats ha...",الشعر‎ -> العناية بالشعر‎ -> تساقط الشعر‎ -> س...,اخرى,Others,No,Seapuri Scalpy Hair Serum 20 ml 0 2500...
3,https://www.storeakmedia.com/storeak-erp/Store...,390185,عطر جانيميد اودي بارفيوم 50 مل,Ganymede EDP 50 ml,3770006409141,NaN,0,"عطر شرقي حار للجنسين.\nمقدمة العطر: البخور, ال...",An oriental spicy fragrance for both sexes.\nT...,"العطور‎ -> نسائي‎ -> العطور,العطور‎ -> رجالي‎ ...",مارك انطوان باروا باريس,Marc-Antoine Barrois Paris,No,Ganymede EDP 50 ml 0 25000\n1 3...
4,https://www.storeakmedia.com/storeak-erp/Store...,390177,جل تصفيف الحواجب مع الببتيدات 15 مل,Brow Styling Gel With Peptides 15 ml,8056814230036,NaN,15000,امنحي حواجبك شكلاً أنيقًا يدوم طوال اليوم مع ج...,"Give your brows a sleek, all day shape with ou...",المكياج‎ -> الحواجب‎ -> جل,آيتن,Ayten,No,Brow Styling Gel With Peptides 15 ml 0 ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24697,https://www.storeakmedia.com/storeak-erp/Store...,315019,معطر الشعر والجسم بالليمون والماتشا 150 مل,Lime & Matcha Hair & Body Mist 150 ml,5028197838058,0,16500,"زذاذ معطر الجسم والشعر منعش وفواح, يتكون من مز...","A refreshing and fragrant body and hair mist, ...",العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No,Lime & Matcha Hair & Body Mist 150 ml 0 ...
24698,https://www.storeakmedia.com/storeak-erp/Store...,315018,معطر الشعر والجسم بالفلفل الوردي والليتشي 150 مل,Pink Pepper & Lychee Hair & Body Mist 150 ml,5028197930516,0,12000,"رذاذ معطر الجسم والشعر جذاب ومنعش للنساء, يمتا...",An attractive and refreshing body and hair mis...,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No,Pink Pepper & Lychee Hair & Body Mist 150 ml 0...
24699,https://www.storeakmedia.com/storeak-erp/Store...,314993,ماسكارا جلام اند دول تعزز نمو الرموش 8 مل,Glam & Doll Boost Lash Growth Volume Mascara 8 ml,4059729191380,0,10500,"ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...","Mascara features a brush with thick bristles, ...",المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,كاتريس,Catrice,No,Glam & Doll Boost Lash Growth Volume Mascara 8...
24700,https://www.storeakmedia.com/storeak-erp/Store...,314992,مست الجسم باشن فروت 150 مل,Body Mist Passion Fruit150 ml,5283024103017,0,15000,"رذاذ معطر للجسم, يساعدك على الشعور بالانتعاش و...",A body mist that helps you feel fresh and conf...,"العناية بالجسم‎ -> سبلاش,private group‎ -> مين...",بيت الصابون اللبناني,Bayt Al Saboun,No,Body Mist Passion Fruit150 ml 0 25000\...
24701,https://www.storeakmedia.com/storeak-erp/Store...,314991,ماسكارا فائقة الكثافة (1أسود) 15 مل,Volume Supreme Mascara (1Black) 15 ml,4052136039429,0,22500,"ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...",Mascara is characterized by its thick bristled...,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,آرتديكو,Artdeco,No,Volume Supreme Mascara (1Black) 15 ml 0 ...