In [6]:
from dataclasses import replace

import pandas as pd

In [7]:
sr=pd.Series(["a","b","c"])

In [8]:
sr

0    a
1    b
2    c
dtype: str

In [9]:
sr1=pd.Series(["ahmad","python","class"],index=["*","=","!"])#optional perimeter index

In [10]:
sr1

*     ahmad
=    python
!     class
dtype: str

In [11]:
print("ahmad",end="")#print command perimeterr

ahmad

In [12]:
sr2=pd.Series(["val1","val2","val3"],index=["*","=","(_)"])
sr2

*      val1
=      val2
(_)    val3
dtype: str

In [13]:
di={"name":["ali","ahmad","arbab"],"age":[21,22,23]}
di

{'name': ['ali', 'ahmad', 'arbab'], 'age': [21, 22, 23]}

In [14]:
df=pd.DataFrame(di)#dataframe short variable

In [15]:
df

    name  age
0    ali   21
1  ahmad   22
2  arbab   23

In [16]:
df.to_csv("ClasFirstTable.csv")

In [17]:
dfItems=pd.read_excel("VendorProducts.xlsx")

In [18]:
dfItems

,Picture,Id,Name,Secondary Name,Barcode,Code,Price,Description,Secondary Description,Sub Description,Secondary Sub Description,Menu,Brand,Secondary Brand,Has Collections
0,https://www.storeakmedia.com/storeak-erp/Store...,390188,زيت الشفاه بليجر 001، 5 مل,"Pleasure Lip Oil 001, 5 ml",8011607402304,NaN,"25,000د.ع","زيت مغذي للشفاه, يُعزز لمعان الشفاه بتأثير بصر...",Nourishing lip oil that enhances lip shine wit...,|بوبا ميلانو|Pupa Milano|Lip Oil|زيت الشفاه|زي...,NaN,العناية بالبشرة‎ -> الشفاه‎ -> زيوت,بوبا ميلانو,Pupa Milano,No
1,https://www.storeakmedia.com/storeak-erp/Store...,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,NaN,"300,000د.ع",عطر أروماتك إنيق للرجال.\nمكونات العطر: العنبر...,An elegant aromatic fragrance for men.\nFragra...,|شانيل|Chanel|العطور|Perfumes|عطر للرجال|عطر ر...,NaN,"العطور‎ -> رجالي‎ -> العطور,private group‎ -> ...",شانيل,Chanel,Yes
2,https://www.storeakmedia.com/storeak-erp/Store...,390186,سيروم الشعر لفروة الرأس سيابوري 20 مل,Seapuri Scalpy Hair Serum 20 ml,8809934860870,NaN,"30,000د.ع",سيروم خفيف الوزن وغير دهني يعالج تساقط الشعر و...,"A lightweight, non greasy serum that treats ha...",|Others|اخرى|hair loss Serum|سيروم تساقط الشعر...,NaN,الشعر‎ -> العناية بالشعر‎ -> تساقط الشعر‎ -> س...,اخرى,Others,No
3,https://www.storeakmedia.com/storeak-erp/Store...,390185,عطر جانيميد اودي بارفيوم 50 مل,Ganymede EDP 50 ml,3770006409141,NaN,00د.ع,"عطر شرقي حار للجنسين.\nمقدمة العطر: البخور, ال...",An oriental spicy fragrance for both sexes.\nT...,|Marc-Antoine Barois Paris|مارك أنطوان باروا ب...,NaN,"العطور‎ -> نسائي‎ -> العطور,العطور‎ -> رجالي‎ ...",مارك انطوان باروا باريس,Marc-Antoine Barrois Paris,No
4,https://www.storeakmedia.com/storeak-erp/Store...,390177,جل تصفيف الحواجب مع الببتيدات 15 مل,Brow Styling Gel With Peptides 15 ml,8056814230036,NaN,"15,000د.ع",امنحي حواجبك شكلاً أنيقًا يدوم طوال اليوم مع ج...,"Give your brows a sleek, all day shape with ou...",|Ayten|أيتن|Eyebrow Gel|جل الحواجب|جل تصفيف ال...,NaN,المكياج‎ -> الحواجب‎ -> جل,آيتن,Ayten,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24697,https://www.storeakmedia.com/storeak-erp/Store...,315019,معطر الشعر والجسم بالليمون والماتشا 150 مل,Lime & Matcha Hair & Body Mist 150 ml,5028197838058,0,"16,500د.ع","زذاذ معطر الجسم والشعر منعش وفواح, يتكون من مز...","A refreshing and fragrant body and hair mist, ...",|ذا بودي شوب|The Body Shop|عطور الشعر|Hair Per...,NaN,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24698,https://www.storeakmedia.com/storeak-erp/Store...,315018,معطر الشعر والجسم بالفلفل الوردي والليتشي 150 مل,Pink Pepper & Lychee Hair & Body Mist 150 ml,5028197930516,0,"12,000د.ع","رذاذ معطر الجسم والشعر جذاب ومنعش للنساء, يمتا...",An attractive and refreshing body and hair mis...,|ذا بودي شوب|The Body Shop|عطور الشعر|Hair Per...,NaN,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24699,https://www.storeakmedia.com/storeak-erp/Store...,314993,ماسكارا جلام اند دول تعزز نمو الرموش 8 مل,Glam & Doll Boost Lash Growth Volume Mascara 8 ml,4059729191380,0,"10,500د.ع","ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...","Mascara features a brush with thick bristles, ...",|كاتريس|Catrice|ماسكارا عادية| Mascara‎ Normal...,NaN,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,كاتريس,Catrice,No
24700,https://www.storeakmedia.com/storeak-erp/Store...,314992,مست الجسم باشن فروت 150 مل,Body Mist Passion Fruit150 ml,5283024103017,0,"15,000د.ع","رذاذ معطر للجسم, يساعدك على الشعور بالانتعاش و...",A body mist that helps you feel fresh and conf...,|بيت الصابون اللبناني|Bayt Al Saboun|العناية ب...,NaN,"العناية بالجسم‎ -> سبلاش,private group‎ -> مين...",بيت الصابون اللبناني,Bayt Al Saboun,No
24701,https://www.storeakmedia.com/storeak-erp/Store...,314991,ماسكارا فائقة الكثافة (1أسود) 15 مل,Volume Supreme Mascara (1Black) 15 ml,4052136039429,0,"22,500د.ع","ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...",Mascara is characterized by its thick bristled...,|آرتديكو|Artdeco|ماسكارا عادية| Mascara‎ Norma...,NaN,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,آرتديكو,Artdeco,No

In [19]:
dfItems=pd.read_excel("VendorProducts.xlsx",sheet_name="Items")
dfItems

,Picture,Id,Name,Secondary Name,Barcode,Code,Price,Description,Secondary Description,Sub Description,Secondary Sub Description,Menu,Brand,Secondary Brand,Has Collections
0,https://www.storeakmedia.com/storeak-erp/Store...,390188,زيت الشفاه بليجر 001، 5 مل,"Pleasure Lip Oil 001, 5 ml",8011607402304,NaN,"25,000د.ع","زيت مغذي للشفاه, يُعزز لمعان الشفاه بتأثير بصر...",Nourishing lip oil that enhances lip shine wit...,|بوبا ميلانو|Pupa Milano|Lip Oil|زيت الشفاه|زي...,NaN,العناية بالبشرة‎ -> الشفاه‎ -> زيوت,بوبا ميلانو,Pupa Milano,No
1,https://www.storeakmedia.com/storeak-erp/Store...,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,NaN,"300,000د.ع",عطر أروماتك إنيق للرجال.\nمكونات العطر: العنبر...,An elegant aromatic fragrance for men.\nFragra...,|شانيل|Chanel|العطور|Perfumes|عطر للرجال|عطر ر...,NaN,"العطور‎ -> رجالي‎ -> العطور,private group‎ -> ...",شانيل,Chanel,Yes
2,https://www.storeakmedia.com/storeak-erp/Store...,390186,سيروم الشعر لفروة الرأس سيابوري 20 مل,Seapuri Scalpy Hair Serum 20 ml,8809934860870,NaN,"30,000د.ع",سيروم خفيف الوزن وغير دهني يعالج تساقط الشعر و...,"A lightweight, non greasy serum that treats ha...",|Others|اخرى|hair loss Serum|سيروم تساقط الشعر...,NaN,الشعر‎ -> العناية بالشعر‎ -> تساقط الشعر‎ -> س...,اخرى,Others,No
3,https://www.storeakmedia.com/storeak-erp/Store...,390185,عطر جانيميد اودي بارفيوم 50 مل,Ganymede EDP 50 ml,3770006409141,NaN,00د.ع,"عطر شرقي حار للجنسين.\nمقدمة العطر: البخور, ال...",An oriental spicy fragrance for both sexes.\nT...,|Marc-Antoine Barois Paris|مارك أنطوان باروا ب...,NaN,"العطور‎ -> نسائي‎ -> العطور,العطور‎ -> رجالي‎ ...",مارك انطوان باروا باريس,Marc-Antoine Barrois Paris,No
4,https://www.storeakmedia.com/storeak-erp/Store...,390177,جل تصفيف الحواجب مع الببتيدات 15 مل,Brow Styling Gel With Peptides 15 ml,8056814230036,NaN,"15,000د.ع",امنحي حواجبك شكلاً أنيقًا يدوم طوال اليوم مع ج...,"Give your brows a sleek, all day shape with ou...",|Ayten|أيتن|Eyebrow Gel|جل الحواجب|جل تصفيف ال...,NaN,المكياج‎ -> الحواجب‎ -> جل,آيتن,Ayten,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24697,https://www.storeakmedia.com/storeak-erp/Store...,315019,معطر الشعر والجسم بالليمون والماتشا 150 مل,Lime & Matcha Hair & Body Mist 150 ml,5028197838058,0,"16,500د.ع","زذاذ معطر الجسم والشعر منعش وفواح, يتكون من مز...","A refreshing and fragrant body and hair mist, ...",|ذا بودي شوب|The Body Shop|عطور الشعر|Hair Per...,NaN,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24698,https://www.storeakmedia.com/storeak-erp/Store...,315018,معطر الشعر والجسم بالفلفل الوردي والليتشي 150 مل,Pink Pepper & Lychee Hair & Body Mist 150 ml,5028197930516,0,"12,000د.ع","رذاذ معطر الجسم والشعر جذاب ومنعش للنساء, يمتا...",An attractive and refreshing body and hair mis...,|ذا بودي شوب|The Body Shop|عطور الشعر|Hair Per...,NaN,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24699,https://www.storeakmedia.com/storeak-erp/Store...,314993,ماسكارا جلام اند دول تعزز نمو الرموش 8 مل,Glam & Doll Boost Lash Growth Volume Mascara 8 ml,4059729191380,0,"10,500د.ع","ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...","Mascara features a brush with thick bristles, ...",|كاتريس|Catrice|ماسكارا عادية| Mascara‎ Normal...,NaN,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,كاتريس,Catrice,No
24700,https://www.storeakmedia.com/storeak-erp/Store...,314992,مست الجسم باشن فروت 150 مل,Body Mist Passion Fruit150 ml,5283024103017,0,"15,000د.ع","رذاذ معطر للجسم, يساعدك على الشعور بالانتعاش و...",A body mist that helps you feel fresh and conf...,|بيت الصابون اللبناني|Bayt Al Saboun|العناية ب...,NaN,"العناية بالجسم‎ -> سبلاش,private group‎ -> مين...",بيت الصابون اللبناني,Bayt Al Saboun,No
24701,https://www.storeakmedia.com/storeak-erp/Store...,314991,ماسكارا فائقة الكثافة (1أسود) 15 مل,Volume Supreme Mascara (1Black) 15 ml,4052136039429,0,"22,500د.ع","ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...",Mascara is characterized by its thick bristled...,|آرتديكو|Artdeco|ماسكارا عادية| Mascara‎ Norma...,NaN,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,آرتديكو,Artdeco,No

In [20]:

print(dfItems["Item Name"])

KeyError: 'Item Name'

In [ ]:
dfItems=pd.read_excel("VendorProducts.xlsx",sheet_name="Collections")
dfItems

In [ ]:
print(dfItems["Price"])

In [ ]:
for i in dfItems["Price"]:
    print(int(i.replace("د.ع","").replace(",","")))

In [ ]:
dfItems.info()
#has collections

In [ ]:
dfItems.describe()

In [ ]:
dfItems.head()

In [ ]:
dfItems.tail()

In [ ]:
dfItems.fillna("")

In [ ]:
#indexing with column
dfItems["Picture"]

In [ ]:
dfItems[["Picture","Id","Name"]]

In [ ]:
dfItems["Name"].fillna("")

In [ ]:
info={"Username":["sik_1=2514"],"Age":"19","Class":"pyton"}
df=pd.DataFrame(info)
df

In [ ]:
df.to_csv("info.csv")

In [ ]:
df.to_csv("info.csv",index=False)

In [ ]:
info=pd.read_csv("info.csv")

In [ ]:
info

In [ ]:
#row get from index
info.loc[0]

In [ ]:
print(len(info))

In [ ]:
print(len(info["Username"]))
currentrowNumber=len(info["Username"])
info.loc[currentrowNumber]=["ali","20","java"]

In [ ]:
info1=info

In [ ]:
info1.to_csv("info1.csv",index=False)

In [ ]:
info1

In [ ]:
import pandas as pd

di = {"name": [], "age": [], "amount": {}}

while True:
    print("\n1. Register Account")
    print("2. Exit")

    ch = input("Enter your choice 1(create) or 2(exit): ")

    if ch == "1":
        nm = input("Enter name: ")

        if nm in di["name"]:
            print("Name already registered!")
            continue

        ag = int(input("Enter your age: "))

        di["name"].append(nm)
        di["age"].append(ag)
        di["amount"][nm] = 5000

        print("Account created successfully!")
        print("Default balance:", di["amount"][nm])

        while True:
            print("\n3. Withdraw Money")
            print("4. Deposit Money")
            print("5. Check Balance")
            print("6. Exit")

            ch2 = input("Enter your choice 3 (to withdraw) or 4 (to deposit money) 5(current balance) 6(exit): ")

            if ch2 == "3":
                withdraw = int(input("Enter amount to withdraw: "))

                if withdraw <= di["amount"][nm]:
                    di["amount"][nm] -= withdraw
                    print("Withdrawal successful!")
                    print("Remaining balance:", di["amount"][nm])
                else:
                    print("Insufficient balance!")

            elif ch2 == "4":
                deposit = int(input("Enter amount to deposit: "))
                di["amount"][nm] += deposit
                print("Deposit successful!")
                print("Updated balance:", di["amount"][nm])

            elif ch2 == "5":
                print("Current balance:", di["amount"][nm])

            elif ch2 == "6":
                break

            else:
                print("Invalid choice!")

    elif ch == "2":
        print("Thank you!")
        break

    else:
        print("Invalid option!")

# Save data to CSV
df = pd.DataFrame({
    "name": di["name"],
    "age": di["age"],
    "amount": [di["amount"][name] for name in di["name"]]
})

df.to_csv("accountinfo.csv", index=False)

In [ ]:
info=pd.read_csv("accountinfo.csv")
info

In [ ]:
import pandas as pd

# dictionary to store data
di = {"name": [], "age": [], "amount": {}}

def save_to_csv():
    df = pd.DataFrame({
        "name": di["name"],
        "age": di["age"],
        "amount": [di["amount"][name] for name in di["name"]]
    })
    df.to_csv("accountinfo.csv", index=False)


while True:
    print("\n1. Register Account")
    print("2. Exit")

    ch = input("Enter your choice 1(create) or 2(exit) : ")

    if ch == "1":
        nm = input("Enter name: ")

        if nm in di["name"]:
            print("Name already registered!")
            continue

        ag = int(input("Enter your age: "))

        di["name"].append(nm)
        di["age"].append(ag)
        di["amount"][nm] = 5000

        save_to_csv()

        print("Account created successfully!")
        print("Default balance:", di["amount"][nm])

        while True:
            print("\n3. Withdraw Money")
            print("4. Deposit Money")
            print("5. Check Balance")
            print("6. Exit")

            ch2 = input("Enter your choice: 3(withdraw)4(deposit )5(current balence) 6(exit)")

            if ch2 == "3":
                withdraw = int(input("Enter amount to withdraw: "))

                if withdraw <= di["amount"][nm]:
                    di["amount"][nm] -= withdraw
                    save_to_csv()
                    print("Withdrawal successful!")
                    print("Remaining balance:", di["amount"][nm])
                else:
                    print("Insufficient balance!")

            elif ch2 == "4":
                deposit = int(input("Enter amount to deposit: "))
                di["amount"][nm] += deposit
                save_to_csv()  # save after deposit
                print("Deposit successful!")
                print("Updated balance:", di["amount"][nm])

            elif ch2 == "5":
                print("Current balance:", di["amount"][nm])

            elif ch2 == "6":
                break

            else:
                print("Invalid choice!")

    elif ch == "2":
        print("Thank you!")
        break

    else:
        print("Invalid option!")

In [ ]:
import pandas as pd

# dictionary to store data
di = {"name": [], "age": [], "amount": {}}

def save_to_csv():
    df = pd.DataFrame({
        "name": di["name"],
        "age": di["age"],
        "amount": [di["amount"][name] for name in di["name"]]
    })
    df.to_csv("accountinfo.csv", index=False)
while True:
    print("\n1. Register Account")
    print("2. Exit")

    ch = input("Enter your choice 1(create) or 2(exit) : ")

    if ch == "1":
        nm = input("Enter name: ")

        if nm in di["name"]:
            print("Name already registered!")
            continue

        ag = int(input("Enter your age: "))

        di["name"].append(nm)
        di["age"].append(ag)
        di["amount"][nm] = 5000

        save_to_csv()

        print("Account created successfully!")
        print("Default balance:", di["amount"][nm])
        while True:
            print("\n3. Withdraw Money")
            print("4. Deposit Money")
            print("5. Check Balance")
            print("6. Exit")

            ch2 = input("Enter your choice: 3(withdraw)4(deposit )5(current balence) 6(exit)")
            if ch2 == "3":
                withdraw = int(input("Enter amount to withdraw: "))

                if withdraw <= di["amount"][nm]:
                    di["amount"][nm] -= withdraw
                    save_to_csv()
                    print("Withdrawal successful!")
                    print("Remaining balance:", di["amount"][nm])
                else:
                    print("Insufficient balance!")

            elif ch2 == "4":
                deposit = int(input("Enter amount to deposit: "))
                di["amount"][nm] += deposit
                save_to_csv()  # save after deposit
                print("Deposit successful!")
                print("Updated balance:", di["amount"][nm])

            elif ch2 == "5":
                print("Current balance:", di["amount"][nm])

            elif ch2 == "6":
                break

            else:
                print("Invalid choice!")

    elif ch == "2":
        print("Thank you!")
        break

    else:
        print("Invalid option!")

In [ ]:
info=pd.read_csv("accountinfo.csv")
info

In [ ]:
import pandas as pd
import random as rd

# dictionary to store data
di = {"name": [], "Account_number": [], "amount": {}}

data_DB=df.to_csv("accountinfo.csv", index=False)
while(True):
    print("enter 1 for account creating \n enter 2 for check balance \n enter 3 for withdraw amount \n enter 4 for deposit money \n enter 5 for exit")
    ch = input("Enter your choice: ")
    if ch==1:
        print("Account creation ")
        no=rd.randint()
        for no in di["Account_number"]:
            no1=rd.randint(no)
    elif ch==2:
        print("Check Balance")
    elif ch==3:
        print("Withdraw Money")
    elif ch==4:
        print("Deposit Money")
    elif ch==5:
        print("Exiting")
    else:
        print("Invalid choice!")

In [ ]:
import pandas as pd
import os

file_name = "bank_accounts.csv"

# Create CSV file if it does not exist
if not os.path.exists(file_name):
    df = pd.DataFrame(columns=["AccountNumber", "Name", "Balance"])
    df.to_csv(file_name, index=False)


def create_account():
    df = pd.read_csv(file_name)

    acc_no = input("Enter Account Number: ")

    # Check if account already exists
    if acc_no in df["AccountNumber"].astype(str).values:
        print("Account already exists!")
        return

    name = input("Enter Customer Name: ")
    balance = float(input("Enter Initial Balance: "))

    new_account = pd.DataFrame({
        "AccountNumber": [acc_no],
        "Name": [name],
        "Balance": [balance]
    })

    df = pd.concat([df, new_account], ignore_index=True)
    df.to_csv(file_name, index=False)

    print("Account created successfully.")


def deposit_money():
    df = pd.read_csv(file_name)

    acc_no = input("Enter Account Number: ")
    amount = float(input("Enter Deposit Amount: "))

    if acc_no in df["AccountNumber"].astype(str).values:
        index = df[df["AccountNumber"].astype(str) == acc_no].index[0]
        df.at[index, "Balance"] += amount
        df.to_csv(file_name, index=False)
        print("Deposit successful.")
    else:
        print("Account not found.")


def withdraw_money():
    df = pd.read_csv(file_name)

    acc_no = input("Enter Account Number: ")
    amount = float(input("Enter Withdrawal Amount: "))

    if acc_no in df["AccountNumber"].astype(str).values:
        index = df[df["AccountNumber"].astype(str) == acc_no].index[0]

        if df.at[index, "Balance"] >= amount:
            df.at[index, "Balance"] -= amount
            df.to_csv(file_name, index=False)
            print("Withdrawal successful.")
        else:
            print("Insufficient Balance.")
    else:
        print("Account not found.")


def check_balance():
    df = pd.read_csv(file_name)

    acc_no = input("Enter Account Number: ")

    if acc_no in df["AccountNumber"].astype(str).values:
        index = df[df["AccountNumber"].astype(str) == acc_no].index[0]
        balance = df.at[index, "Balance"]
        print("Current Balance:", balance)
    else:
        print("Account not found.")
while True:
    print("\n----- Banking System -----")
    print("1. Create Account")
    print("2. Deposit Money")
    print("3. Withdraw Money")
    print("4. Check Balance")
    print("5. Exit")

    choice = input("Enter your choice: ")

    if choice == "1":
        create_account()

    elif choice == "2":
        deposit_money()

    elif choice == "3":
        withdraw_money()

    elif choice == "4":
        check_balance()

    elif choice == "5":
        print("Thank you for using the Banking System.")
        break

    else:
        print("Invalid choice. Please try again.")

In [ ]:
import random as rd
while True:
    choice = int(input("Enter 1 for account Opening \n Enter 2 for Balance Check \n Enter 3 for WithDrawl \n Enter 4 for Deposit: \n Enter 5 for Exit:"))
    if choice ==1:
        userDB = pd.read_csv("Bank.csv")
        userName = input("Enter User Name:")
        accNo = rd.randint(10000,99999)
        balance = 5000
        newUserDataList = [accNo,userName,balance]
        currentrowNumber = len(userDB["AccountNumber"])
        userDB.loc[currentrowNumber] = newUserDataList
        userDB.to_csv("Bank.csv",index=False)
        print("Account Created")
    elif choice ==2:
        userDB = pd.read_csv("Bank.csv")
        accNo = int(input("Enter Account Number:"))
        if accNo not in list(userDB["AccountNumber"]):
            print("Account Number Not Found")
            continue
        for i in range(len(userDB)):
            if userDB["AccountNumber"][i] == accNo:
                nm = userDB["FullName"][i]
                print(f"Welcome {nm} \nYour Balance is {userDB['Balance'][i]}")

    elif choice ==3:
        userDB = pd.read_csv("Bank.csv")
        accNo = int(input("Enter Account Number:"))
        if accNo not in list(userDB["AccountNumber"]):
            print("Account Number Not Found")
            continue
        for i in range(len(userDB)):
            if userDB["AccountNumber"][i] == accNo:
                nm = userDB["FullName"][i]
                amount2Wtihdraw = int(input("Enter Amount to Withdraw:"))
                userDB['Balance'][i] = userDB['Balance'][i] - amount2Wtihdraw
                # userDB['Balance'][i] = newBalance
                print(f"Welcome {nm} \nYour new Balance is {userDB['Balance'][i]}")
                userDB.to_csv("Bank.csv",index=False)
    elif choice ==4:
        userDB = pd.read_csv("Bank.csv")
        accNo = int(input("Enter Account Number:"))
        if accNo not in list(userDB["AccountNumber"]):
            print("Account Number Not Found")
            continue
        for i in range(len(userDB)):
            if userDB["AccountNumber"][i] == accNo:
                nm = userDB["FullName"][i]
                amount2Wtihdraw = int(input("Enter Amount to Withdraw:"))
                userDB['Balance'][i] = userDB['Balance'][i] + amount2Wtihdraw
                # userDB['Balance'][i] = newBalance
                print(f"Welcome {nm} \nYour new Balance is {userDB['Balance'][i]}")
                userDB.to_csv("Bank.csv",index=False)
    elif choice ==5:
        print("Exiting")
        break

In [ ]:
import pandas as pd

df = pd.read_csv("bank_accounts.csv")

print(df)

In [ ]:
#LMS USERID, USERNAME ,CLASS ,SUBJECT
import pandas as pd
data = {
    "StudentID": [],
    "StudentName": [],
    "class":[],
    "Subjects": []
}

df = pd.DataFrame(data)

df.to_csv("LMS.csv", index=False)

print("CSV file created successfully")
while True:
    choice = int(input("Enter 1 for registration \n Enter 2 for student info fetch \n Enter 3 for Student info update \n Enter 4 for EXIT: "))
    if choice==1:
        print("Student Registration")
        userDB = pd.read_csv("LMS.csv")
        userName = input("Enter Student  Name:")
        userID = int(input("Enter Student ID:"))
        clas=input("Enter Student Class:")
        subjects=input("Enter Student Subjects:")
        newUserDataList = [userID,userName,clas,subjects]
        currentrowNumber = len(userDB["StudentID"])
        userDB.loc[currentrowNumber] = newUserDataList
        userDB.to_csv("LMS.csv",index=False)
        print("Account Created")
    elif choice==2:
        print("Student Info")
        userDB = pd.read_csv("LMS.csv")
        userID = int(input("Enter StudentID:"))
        if userID not in list(userDB["StudentID"]):
            print("ID Not Found")
            continue
        for i in range(len(userID)):
            if userDB["StudentID"][i] == userID:
                nm = userDB["StudentName"][i]
                print(f"Welcome {userName} \nYour ID is {userDB['StudentID'][i]}")

    elif choice==3:
        print("Student Info Update")
    elif choice==4:
        print("EXIT")
    else:
        print("Invalid choice. Please try again.")

In [ ]:
import pandas as pd

data = {
    "StudentID": [],
    "StudentName": [],
    "class": [],
    "Subjects": []
}

df = pd.DataFrame(data)
df.to_csv("LMS.csv", index=False)

print("CSV file created successfully")

while True:

    choice = int(input("\nEnter 1 for registration"
                       "\nEnter 2 for student info fetch"
                       "\nEnter 3 for student info update"
                       "\nEnter 4 for EXIT\n"))


    if choice == 1:
        print("Student Registration")

        userDB = pd.read_csv("LMS.csv")

        userName = input("Enter Student Name: ")
        userID = int(input("Enter Student ID: "))
        clas = input("Enter Student Class: ")
        subjects = input("Enter Student Subjects: ")

        newUserDataList = [userID, userName, clas, subjects]

        currentrowNumber = len(userDB["StudentID"])

        userDB.loc[currentrowNumber] = newUserDataList

        userDB.to_csv("LMS.csv", index=False)

        print("Account Created")


    elif choice == 2:
        print("Student Info")

        userDB = pd.read_csv("LMS.csv")

        userID = int(input("Enter StudentID: "))
        if userID not in list(userDB["StudentID"]):#SERIES Ma data bool k through nhi print
            print("ID Not Found")
            continue

        for i in range(len(userDB)):
            if userDB["StudentID"][i] == userID:
                nm = userDB["StudentName"][i]
                clas = userDB["class"][i]
                sub = userDB["Subjects"][i]

                print(f"\nWelcome {nm}")
                print("Student ID:", userID)
                print("Class:", clas)
                print("Subjects:", sub)


    elif choice == 3:
        print("Student Info Update")

        userDB = pd.read_csv("LMS.csv")

        userID = int(input("Enter StudentID to update: "))

        if userID not in list(userDB["StudentID"]):
            print("ID Not Found")
            continue

        for i in range(len(userDB)):
            if userDB["StudentID"][i] == userID:

                newName = input("Enter new name: ")
                newClass = input("Enter new class: ")
                newSub = input("Enter new subjects: ")

                userDB.loc[i, "StudentName"] = newName
                userDB.loc[i, "class"] = newClass
                userDB.loc[i, "Subjects"] = newSub

                userDB.to_csv("LMS.csv", index=False)

                print("Student Record Updated")


    elif choice == 4:
        print("EXIT")
        break

    else:
        print("Invalid choice. Please try again.")

In [ ]:
import pandas as pd

df = pd.read_csv("LMS.csv")

print(df)

In [ ]:
StudentAccountDictionary = {"StudentId":["10001","10002","10003"],"StudentName":["Ahmad","Ali","yth"],"StudentClass":["1","2","3"],"Subjects":[["Math","English","Science"],["Math","Chemistry","Science"],["islamicStudies","English","Physics"]]}

In [ ]:
studentDF = pd.DataFrame(StudentAccountDictionary)

In [ ]:
studentDF

In [ ]:
import pandas as pd
import random as rd
while True:
    choice = input("Enter 1 for Student Registration \n Enter 2 for Student Information Fetch \n Enter 3 for Student Information Update \n Enter 4 for Exit:")
    if choice == "1":
        print("Student Registration")
        userDB = pd.read_csv("LMS.csv")
        userName = input("Enter User Name:")
        studentId = rd.randint(10000,99999)
        newUserDataList = [studentId,StudentName,clas,subjects]
        currentrowNumber = len(userDB["studentID"])
        userDB.loc[currentrowNumber] = newUserDataList
        userDB.to_csv("LMS.csv",index=False)
        print("Account Created")

    elif choice =="2":
        print("======Student Information Fetch========")
        studentDF = pd.read_csv("StudentData.csv")
        studentId = int(input("Enter Student Id:"))
        if studentId not in list(studentDF["StudentId"]):
            print("Student Id Not Found")
            continue
        for i in range(len(studentDF)):
            if studentDF["StudentId"][i] == studentId:
                print(f"Student Name : {studentDF['StudentName'][i]}")
                print(f"Student Class : {studentDF['StudentClass'][i]}")
                print(f"Student Subjects : {studentDF['Subjects'][i]}")
        print("======Student Information Fetch========")
    elif choice =="3":
        print("======Student Information Update=======")
        studentDF = pd.read_csv("StudentData.csv")
        studentId = int(input("Enter Student Id:"))
        if studentId not in list(studentDF["StudentId"]):
            print("Student Id Not Found")
            continue
        for i in range(len(studentDF)):
            if studentDF["StudentId"][i] == studentId:
                print("What do you want to update?")
                updateChoice = input("Enter 1 for Student Name \n Enter 2 for Student Class \n Enter 3 for Student Subjects:")
                if updateChoice == "1":
                    newStudentName = input("Enter New Student Name:")
                    studentDF['StudentName'][i] = newStudentName
                    print(f"Student Name Updated to {newStudentName}")
                elif updateChoice == "2":
                    newStudentClass = input("Enter New Student Class:")
                    studentDF['StudentClass'][i] = newStudentClass
                    print(f"Student Class Updated to {newStudentClass}")
                elif updateChoice == "3":
                        break
                elif choice =="4":
                    print("Exiting")
        break

In [29]:
dfItems.loc[1,"Secondary Name"]

"Bleu De Chanel L'Exclusif Parfum"

In [23]:
dfItems.loc[1:10,["Secondary Name"]]

                                       Secondary Name
1                    Bleu De Chanel L'Exclusif Parfum
2                     Seapuri Scalpy Hair Serum 20 ml
3                                  Ganymede EDP 50 ml
4               Brow Styling Gel With Peptides 15 ml
5                             Limitless Mascara 10 ml
6                                  Eyebrow Serum 5 ml
7                               Evadamo Mascara 10 ml
8                        Argan Oil Conditioner 300 ml
9                       Argan Oil Conditioner 1000 ml
10  Professional 1500 W Hair Dryer With 7 Attachments

In [ ]:
dfItems.loc[1:10,["Secondary Name","    Price"]]

In [42]:
dfItems.loc[:10][["Secondary Name", "Description", "Menu", "Brand"]]

,Secondary Name,Description,Menu,Brand
0,"Pleasure Lip Oil 001, 5 ml","زيت مغذي للشفاه, يُعزز لمعان الشفاه بتأثير بصر...",العناية بالبشرة‎ -> الشفاه‎ -> زيوت,بوبا ميلانو
1,Bleu De Chanel L'Exclusif Parfum,عطر أروماتك إنيق للرجال.\nمكونات العطر: العنبر...,"العطور‎ -> رجالي‎ -> العطور,private group‎ -> ...",شانيل
2,Seapuri Scalpy Hair Serum 20 ml,سيروم خفيف الوزن وغير دهني يعالج تساقط الشعر و...,الشعر‎ -> العناية بالشعر‎ -> تساقط الشعر‎ -> س...,اخرى
3,Ganymede EDP 50 ml,"عطر شرقي حار للجنسين.\nمقدمة العطر: البخور, ال...","العطور‎ -> نسائي‎ -> العطور,العطور‎ -> رجالي‎ ...",مارك انطوان باروا باريس
4,Brow Styling Gel With Peptides 15 ml,امنحي حواجبك شكلاً أنيقًا يدوم طوال اليوم مع ج...,المكياج‎ -> الحواجب‎ -> جل,آيتن
5,Limitless Mascara 10 ml,اكتشفي قوة الجاذبية مع الماسكارا المصممة لتعزي...,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,آيتن
6,Eyebrow Serum 5 ml,احصلي على حواجب أكثر كثافة وطولًا مع السيروم ا...,"المكياج‎ -> الحواجب‎ -> ماسكارا & معالج,privat...",آيتن
7,Evadamo Mascara 10 ml,احصلي على رموش مذهلة مع الماسكارا التي تمنحكِ ...,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,آيتن
8,Argan Oil Conditioner 300 ml,"بلسم يحتوي على تركيبة مشبعة بزيت الأرغان, توفر...",الشعر‎ -> العناية بالشعر‎ -> جميع انواع الشعر‎...,ارجان ديلوكس
9,Argan Oil Conditioner 1000 ml,"بلسم يحتوي على تركيبة مشبعة بزيت الأرغان, توفر...",الشعر‎ -> العناية بالشعر‎ -> جميع انواع الشعر‎...,ارجان ديلوكس
10,Professional 1500 W Hair Dryer With 7 Attachments,مجفف شعر بخاصية التجفيف السريع، يعتني بالشعر ب...,الشعر‎ -> أجهزة الشعر الكهربائية‎ -> مجفف الشعر,إنزو

In [33]:
dfItems.iloc[-10:][["Secondary Name","Description","Menu","Brand"]]

,Secondary Name,Description,Menu,Brand
24692,Gold khusla Hair Mist 125 ml,"عطر شعر فواح للنساء, يمتاز بتركيبة تحمي الشعر ...","العطور‎ -> نسائي‎ -> عطور الشعر,private group‎...",اطياب المرشود
24693,khusla Pink Hair Perfume 125 ml,"عطر شعر فواح للنساء, يتكون من مزيج رائع من الف...","العطور‎ -> نسائي‎ -> عطور الشعر,private group‎...",اطياب المرشود
24694,Khusla Hair Mist Silver 125 ml,"عطر شعر فواح للنساء, يمتاز بتركيبة تحمي الشعر ...","العطور‎ -> نسائي‎ -> عطور الشعر,private group‎...",اطياب المرشود
24695,Khusla Violet Hair Mist 125 ml,"عطر شعر فواح للنساء, يمتاز بتركيبة تحمي الشعر ...","العطور‎ -> نسائي‎ -> عطور الشعر,private group‎...",اطياب المرشود
24696,Apricot & Agave Hair & Body Mist 150 ml,"زذاذ معطر للجسم والشعر جذاب ومنعش, يمتاز بثبات...",العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب
24697,Lime & Matcha Hair & Body Mist 150 ml,"زذاذ معطر الجسم والشعر منعش وفواح, يتكون من مز...",العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب
24698,Pink Pepper & Lychee Hair & Body Mist 150 ml,"رذاذ معطر الجسم والشعر جذاب ومنعش للنساء, يمتا...",العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب
24699,Glam & Doll Boost Lash Growth Volume Mascara 8 ml,"ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...",المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,كاتريس
24700,Body Mist Passion Fruit150 ml,"رذاذ معطر للجسم, يساعدك على الشعور بالانتعاش و...","العناية بالجسم‎ -> سبلاش,private group‎ -> مين...",بيت الصابون اللبناني
24701,Volume Supreme Mascara (1Black) 15 ml,"ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...",المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,آرتديكو

In [46]:
dfItems[["Secondary Name","Description","Menu","Brand"]].tail(10)

,Secondary Name,Description,Menu,Brand
24692,Gold khusla Hair Mist 125 ml,"عطر شعر فواح للنساء, يمتاز بتركيبة تحمي الشعر ...","العطور‎ -> نسائي‎ -> عطور الشعر,private group‎...",اطياب المرشود
24693,khusla Pink Hair Perfume 125 ml,"عطر شعر فواح للنساء, يتكون من مزيج رائع من الف...","العطور‎ -> نسائي‎ -> عطور الشعر,private group‎...",اطياب المرشود
24694,Khusla Hair Mist Silver 125 ml,"عطر شعر فواح للنساء, يمتاز بتركيبة تحمي الشعر ...","العطور‎ -> نسائي‎ -> عطور الشعر,private group‎...",اطياب المرشود
24695,Khusla Violet Hair Mist 125 ml,"عطر شعر فواح للنساء, يمتاز بتركيبة تحمي الشعر ...","العطور‎ -> نسائي‎ -> عطور الشعر,private group‎...",اطياب المرشود
24696,Apricot & Agave Hair & Body Mist 150 ml,"زذاذ معطر للجسم والشعر جذاب ومنعش, يمتاز بثبات...",العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب
24697,Lime & Matcha Hair & Body Mist 150 ml,"زذاذ معطر الجسم والشعر منعش وفواح, يتكون من مز...",العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب
24698,Pink Pepper & Lychee Hair & Body Mist 150 ml,"رذاذ معطر الجسم والشعر جذاب ومنعش للنساء, يمتا...",العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب
24699,Glam & Doll Boost Lash Growth Volume Mascara 8 ml,"ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...",المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,كاتريس
24700,Body Mist Passion Fruit150 ml,"رذاذ معطر للجسم, يساعدك على الشعور بالانتعاش و...","العناية بالجسم‎ -> سبلاش,private group‎ -> مين...",بيت الصابون اللبناني
24701,Volume Supreme Mascara (1Black) 15 ml,"ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...",المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,آرتديكو